language: python

matrix:
    include:
        - os: linux
          dist: precise
        - os: linux
          dist: trusty
        - os: linux
          sudo: false
script:  python --version; ls virtualenv/;
