language: python

matrix:
    include:
        - os: linux
          dist: precise
        - os: linux
          dist: trusty
        - os: linux
          sudo: false
script:  python --version; 'for p in virtualenv/*.*.*; do echo; source $p/bin/activate; python --version; pip list; done'
