language: python

matrix:
    include:
        - os: osx
        - os: linux
          dist: precise
        - os: linux
          dist: trusty
        - os: linux
          sudo: false
script:  ls -l ~/virtualenv; python --version; python -c 'import sysconfig; print sysconfig.get_config_vars()'; 'for p in virtualenv/*.*.*; do echo; source $p/bin/activate; python --version; pip list; done'
