language: ruby

services:
  - postgresql

before_script:
  - psql -c 'create database travis;' -U postgres;

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
    - sudo: false
    - sudo: required

script: pg_config --version
