language: python

matrix:
    include:
        - os: linux
          dist: precise
        - os: linux
          dist: trusty
        - os: linux
          sudo: false
          env: MYPY=`python --version`

script: true

python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.5-dev" # 3.5 development branch
  - "nightly" # currently points to 3.6-dev
