language: ruby

services:
  - postgresql

before_script:
  - psql -c 'create database travis;' -U postgres;

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
    - sudo: false
    - sudo: required
      dist: precise

script: psql -U travis -d travis 'select version();'
