language: erlang
script: ./run_this.sh
services:
    - elasticsearch
after_script: 'echo $TRAVIS_MARIADB_VERSION'
before_script:
  - mysql -e "create database /*M!50701 IF NOT EXISTS */ gotest;" 
deploy:
    provider: script
    script: 'echo $TRAVIS_MARIADB_VERSION'
